### ISSUE TITLE
[ÉPICO] Implementação da UI do sistema

### ISSUE THREAD

**Issue by nblucas** [Gustavo-kohler/Leilao-Solidario#1]
## Descrição
Feito o design das telas, deve-se implementar a UI pelo React.

A princípio, **não** se deve implementar rotas e autenticação.

## Issues relacionadas
Aqui constam as issues que compõem o épico de desenvolvimento da UI da aplicação. Por favor, atente-se à hierarquia das issues.

- [x] 1. [Implementar o header e navegação lateral](https://github.com/Gustavo-kohler/Leilao-Solidario/issues/12)

**Obs**: Essa issue deve ser implementada primeiro, já que é pré-requisito para várias outras.

----

- [ ] 1. [Implementar a página "Home"](https://github.com/Gustavo-kohler/Leilao-Solidario/issues/2)

----

- [ ] 1. [Implementar a página "Sign In"](https://github.com/Gustavo-kohler/Leilao-Solidario/issues/3)
- [ ] 2. [Implementar a página "Sign Up"](https://github.com/Gustavo-kohler/Leilao-Solidario/issues/4)

----

- [ ] 1. [Implementar a página "List of Auctions"](https://github.com/Gustavo-kohler/Leilao-Solidario/issues/5)

----

- [ ] 1. [Implementar a página "Auction"](https://github.com/Gustavo-kohler/Leilao-Solidario/issues/6)

----

- [ ] 1. [Implementar a página "New Auction"](https://github.com/Gustavo-kohler/Leilao-Solidario/issues/7)

----

- [ ] 1. [Implementar a página "History of My Auctions"](https://github.com/Gustavo-kohler/Leilao-Solidario/issues/8)
- [ ] 2. [Implementar a página "My Auctions"](https://github.com/Gustavo-kohler/Leilao-Solidario/issues/9)

----

- [ ] 1. [Implementar a página "Me"](https://github.com/Gustavo-kohler/Leilao-Solidario/issues/10)

----

- [ ] 1. [Implementar a página "Personal Data"](https://github.com/Gustavo-kohler/Leilao-Solidario/issues/11)

----

- [ ] 1. [Implementar a página "Error 404"](https://github.com/Gustavo-kohler/Leilao-Solidario/issues/13)
